### ISSUE TITLE
"password" not defined

### ISSUE THREAD

**Issue by ghost** [byt3bl33d3r/chrome-decrypter#6]
`[+] Opening LoginDATA
[-] (-2146893813, 'CryptUnprotectData', 'Key not valid for use in specified state.')
Traceback (most recent call last):
  File "<string>", line 39, in <module>
NameError: name 'password' is not defined`

**Comment by OneDollarr** [comment]
+ on windows 7 ERROR Opening LoginDATA [-] (-2146893813, 'CryptUnprotectData', 'Key not valid for use in specified state.') Traceback (most recent call last): File "<string>", line 39, in <module> NameError: name 'password' is not defined
